### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by rajild** [rgarom/angular-visualize-directive#1]
Hi;

Is there any option to show spinner until response comes from jasper server?

**Comment by rgarom** [comment]
Hi rajild,

I've updated the code to implement that functionality.

**Comment by rajild** [comment]
Hi;

Thanks for your quick reply.  I tried using this but code throws error:

ReferenceError: Spinner is not defined
    at link (http://localhost:8100/resources/mobile/js/angular-visualize-directive.js:54:39)
    at http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:104:33
    at Y (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:104:89)
    at S (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:93:52)
    at g (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:85:384)
    at g (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:85:407)
    at S (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:92:498)
    at g (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:85:384)
    at S (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:92:498)
    at g (http://localhost:8100/resources/mobile/lib/ionic/js/ionic.bundle.min.js:85:384) <visualize id="report" resource="report.resource" params="report.params">

at

var spinner = new Spinner(opts).spin(target);

I am using ionic framework.  Any idea?

**Comment by rgarom** [comment]
Thanks for the PR @gavioto!
